In [1]:
#Import Modules
import psycopg2
import sqlalchemy as sal 
from sqlalchemy import create_engine
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Create engine path
engine = create_engine('postgres+psycopg2://postgres:T0nielt1gre@localhost:5432/beer_lovers')

#Connect engine path
conn = engine.connect()

In [9]:
#Choose table from data frame
breweries = pd.read_sql("SELECT * FROM breweries", conn)

categories = pd.read_sql("SELECT * FROM categories", conn)

reviewed_breweries_clean = pd.read_sql("SELECT * FROM reviewed_breweires_clean", conn)

reviewed_breweries = pd.read_sql("SELECT * FROM reviewed_breweries", conn)

In [10]:
breweries.head()

,id,name,address1,address2,city,state,code,country,phone,website,filepath,descript,last_mod
0,1,(512) Brewing Company,"407 Radam, F200",None,Austin,Texas,78745,United States,512.707.2337,http://512brewing.com/,None,(512) Brewing Company is a microbrewery locate...,2010-07-22
1,2,21st Amendment Brewery Cafe,563 Second Street,None,San Francisco,California,94107,United States,1-415-369-0900,http://www.21st-amendment.com/,None,The 21st Amendment Brewery offers a variety of...,2010-10-24
2,3,3 Fonteinen Brouwerij Ambachtelijke Geuzestekerij,Hoogstraat 2A,None,Beersel,Vlaams Brabant,None,Belgium,32-02-/-306-71-03,http://www.3fonteinen.be/index.htm,None,None,2010-07-22
3,4,Aass Brewery,Ole Steensgt. 10 Postboks 1530,None,Drammen,None,None,Norway,47-32-26-60-00,http://www.aass.no,None,Aass Brewery was established in 1834 and is th...,2010-07-22
4,5,Abbaye de Leffe,Dinant,None,Dinant,Namur,None,Belgium,None,None,None,None,2010-07-22

In [12]:
categories.head()

   id            cat_name
0  -1              Unique
1   1         British Ale
2   2           Irish Ale
3   3  North American Ale
4   4          German Ale

In [ ]:
rev